export default {
  colors: [
    {
      color: '#384f83',
      id: 154,
      label: 'Sea',
      logo: require('../resources/seaLogo.png'),
      // logo: require('../resources/tmp/seaLogo2.png'),
    },
    {
      color: '#efefef',
      id: 105,
      label: 'Cloud',
      logo: require('../resources/cloudLogo.png'),
      // logo: require('../resources/tmp/cloudLogo2.png'),
      labelColor: "#d3d3d3"
    },
    {
      color: '#2c1e16',
      id: 110,
      label: 'Dirt',
      logo: require('../resources/dirtLogo.png'),
      // logo: require('../resources/tmp/dirtLogo2.png'),
    },
    {
      color: '#5d6e32',
      id: 96,
      label: 'Bush',
      logo: require('../resources/bushLogo.png'),
      // logo: require('../resources/tmp/bushLogo2.png'),
    },
    // {
    //   color: '#b7d24e',
    //   id: 123,
    //   label: 'grass',
    //   labelColor: 'black',
    //   logo: require('../resources/grassLogo.png'),
    // },
    {
      color: '#3c3b4b',
      id: 134,
      label: 'Mountain',
      logo: require('../resources/mountainLogo.png'),
      // logo: require('../resources/tmp/mountainLogo2.png'),
    },
    // {
    //   color: '#987e6a',
    //   id: 148,
    //   label: 'road',
    //   logo: './resources/roadLogo.png',
    // },
    {
      color: '#759edf',
      id: 156,
      label: 'Sky',
      logo: require('../resources/skyLogo.png'),
      // logo: require('../resources/tmp/skyLogo2.png'),
    },
    {
      color: '#352613',
      id: 168,
      label: 'Tree',
      logo: require('../resources/treeLogo.png'),
      // logo: require('../resources/tmp/treeLogo2.png'),
    },
    // {
    //   color: '#e670b6',
    //   id: 118,
    //   label: 'flower',
    //   logo: './resources/flowerLogo.png',
    // },
    // {
    //   color: '#c1c3c9',
    //   id: 119,
    //   label: 'fog',
    //   logo: './resources/fogLogo.png',
    // },
    {
      color: '#776c2d',
      id: 126,
      label: 'Hill',
      logo: require('../resources/hillLogo.png'),
      // logo: require('../resources/tmp/hillLogo2.png'),
    },
    // {
    //   color: '#bf602c', 
    //   id: 128,
    //   label: 'leaves',
    //   logo: './resources/leavesLogo.png',
    // },
    {
      color: '#32604d',
      id: 147,
      label: 'River',
      logo: require('../resources/riverLogo.png'),
      // logo: require('../resources/tmp/riverLogo2.png'),
    },
    // {
    //   color: '#fafafa',
    //   id: 158,
    //   label: 'snow',
    //   labelColor: 'black',
    //   logo: './resources/snowLogo.png',
    // },
  ],
};
