export default {
  colors: [
    {
      color: '#0907E6',
      id: 154,
      label: 'Sea',
      logo: require('../resources/seaLogo.png'),
      // logo: require('../resources/tmp/seaLogo2.png'),
    },
    {
      color: '#06E6E6',
      id: 105,
      label: 'Cloud',
      logo: require('../resources/cloudLogo.png'),
      // logo: require('../resources/tmp/cloudLogo2.png'),
      labelColor: "#d3d3d3"
    },
    {
      color: '#000AFF',
      id: 110,
      label: 'Dirt',
      logo: require('../resources/dirtLogo.png'),
      // logo: require('../resources/tmp/dirtLogo2.png'),
    },
    {
      color: '#04C803',
      id: 96,
      label: 'Bush',
      logo: require('../resources/bushLogo.png'),
      // logo: require('../resources/tmp/bushLogo2.png'),
    },
    {
      color: '#04FA07',
      id: 123,
      label: 'grass',
      labelColor: 'black',
      logo: require('../resources/bushLogo.png'),
    },
    {
      color: '#8FFF8C',
      id: 134,
      label: 'Mountain',
      logo: require('../resources/mountainLogo.png'),
      // logo: require('../resources/tmp/mountainLogo2.png'),
    },
    // {
    //   color: '#8C8C8C',
    //   id: 148,
    //   label: 'road',
    //   logo: './resources/roadLogo.png',
    // },
    {
      color: '#06E6E6',
      id: 156,
      label: 'Sky',
      logo: require('../resources/skyLogo.png'),
      // logo: require('../resources/tmp/skyLogo2.png'),
    },
    {
      color: '#04C803',
      id: 168,
      label: 'Tree',
      logo: require('../resources/treeLogo.png'),
      // logo: require('../resources/tmp/treeLogo2.png'),
    },
    // {
    //   color: '#c1c3c9',
    //   id: 119,
    //   label: 'fog',
    //   logo: './resources/fogLogo.png',
    // },
    {
      color: '#FF6600',
      id: 126,
      label: 'Hill',
      logo: require('../resources/hillLogo.png'),
      // logo: require('../resources/tmp/hillLogo2.png'),
    },
    // {
    //   color: '#bf602c', 
    //   id: 128,
    //   label: 'leaves',
    //   logo: './resources/leavesLogo.png',
    // },
    {
      color: '#0BC8C8',
      id: 147,
      label: 'River',
      logo: require('../resources/riverLogo.png'),
      // logo: require('../resources/tmp/riverLogo2.png'),
    },
    {
      color: '#000000',
      id: 100,
      label: 'user brush',
      // logo: './resources/flowerLogo.png',
    },
    // {
    //   color: '#fafafa',
    //   id: 158,
    //   label: 'snow',
    //   labelColor: 'black',
    //   logo: './resources/snowLogo.png',
    // },
  ],
};
