export default {
  colors: [
    {
      color: '#384f83',
      id: 154,
      label: 'sea',
      logo: require('../resources/seaLogo.png'),
    },
    {
      color: '#efefef',
      id: 105,
      label: 'cloud',
      logo: require('../resources/cloudLogo.png'),
    },
    {
      color: '#2c1e16',
      id: 110,
      label: 'dirt',
      logo: require('../resources/dirtLogo.png'),
    },
    {
      color: '#5d6e32',
      id: 96,
      label: 'bush',
      logo: require('../resources/bushLogo.png'),
    },
    // {
    //   color: '#b7d24e',
    //   id: 123,
    //   label: 'grass',
    //   labelColor: 'black',
    //   logo: require('../resources/grassLogo.png'),
    // },
    {
      color: '#3c3b4b',
      id: 134,
      label: 'mountain',
      logo: require('../resources/mountainLogo.png'),
    },
    // {
    //   color: '#987e6a',
    //   id: 148,
    //   label: 'road',
    //   logo: './resources/roadLogo.png',
    // },
    {
      color: '#759edf',
      id: 156,
      label: 'sky',
      logo: require('../resources/skyLogo.png'),
    },
    {
      color: '#352613',
      id: 168,
      label: 'tree',
      logo: require('../resources/treeLogo.png'),
    },
    // {
    //   color: '#e670b6',
    //   id: 118,
    //   label: 'flower',
    //   logo: './resources/flowerLogo.png',
    // },
    // {
    //   color: '#c1c3c9',
    //   id: 119,
    //   label: 'fog',
    //   logo: './resources/fogLogo.png',
    // },
    {
      color: '#776c2d',
      id: 126,
      label: 'hill',
      logo: require('../resources/hillLogo.png'),
    },
    // {
    //   color: '#bf602c',
    //   id: 128,
    //   label: 'leaves',
    //   logo: './resources/leavesLogo.png',
    // },
    {
      color: '#32604d',
      id: 147,
      label: 'river',
      logo: require('../resources/riverLogo.png'),
    },
    // {
    //   color: '#fafafa',
    //   id: 158,
    //   label: 'snow',
    //   labelColor: 'black',
    //   logo: './resources/snowLogo.png',
    // },
  ],
};
